#!/bin/bash
ROOT="$(git rev-parse --show-toplevel)"
CONTENT="$ROOT/content"
LIB="$ROOT/lib"
STATIC="$ROOT/static"
if [ "$CONTENT" = "/content" ]; then
  echo "[ERROR] we failed to get the root directory of the repo before modifying"
  exit 1
fi

echo '[INFO] Compiling content into content dir'
rm -rf "$CONTENT"
mkdir "$CONTENT"
cp -r "$STATIC"/* "$CONTENT/"
cp -r "$LIB" "$CONTENT/"
git add "$CONTENT"
echo '[INFO] Done compiling'
