#!/bin/bash
ROOT="$(git rev-parse --show-toplevel)"
JS="$ROOT/js"
LIB="$ROOT/lib"
STATIC="$ROOT/static"
if [ "$JS" = "/js" ]; then
  echo "[ERROR] we failed to get the root directory of the repo before modifying"
  exit 1
fi

echo '[INFO] Compiling content into content dir'
rm -rf "$JS"
mkdir "$JS"
cp -r "$LIB" "$JS/"
git add "$JS"
echo '[INFO] Done compiling'
