#!/bin/bash
ROOT="$(git rev-parse --show-toplevel)"
HOOKS="$ROOT/.git/hooks"
PRECOMMIT="$HOOKS/pre-commit"
if [ "$HOOKS" = '/.git/hooks' ]; then
  echo "ROOT DIRECTORY FAILED TO BE FOUND"
  exit 1
fi
echo '#!/bin/bash
ROOT="$(git rev-parse --show-toplevel)"
exec $ROOT/compile' > $PRECOMMIT 

chmod 755 $PRECOMMIT
