#!/bin/bash
ROOT="$(git rev-parse --show-toplevel)"
HOOKS="$ROOT/.git/hooks"
POSTCOMMIT="$HOOKS/post-commit"
if [ "$HOOKS" = '/.git/hooks' ]; then
  echo "ROOT DIRECTORY FAILED TO BE FOUND"
  exit 1
fi
echo '#!/bin/bash
if [ "$POSTCOMMITING" != 1 ]; then
  ROOT="$(git rev-parse --show-toplevel)"
  export POSTCOMMITING=1
  "$ROOT/compile"
  if [ "$?" = "0" ]; then
    echo "[INFO] post commit compile and recommit successful"
  else
    echo "[ERROR] post commit compile and recommit failed"
    exit 1
  fi
fi' > $POSTCOMMIT 

chmod 755 $POSTCOMMIT
